#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=31gb,walltime=02:00:00

set -e
set -x

#execute app
if [ -f 'track_aligned/track.tck' ]; then 
    echo "Tractogram already registered in MNI space."
else 
	echo "Registering the tractogram to the MNI152 T1 template with ANTs..."
	singularity exec -e docker://giuliaberto/ants2-mrtrix3-fsl6:1.1 ./run_registration.sh
fi

echo "No examples provided. STARTING TEST..."
singularity exec -e docker://brainlife/dipy:0.16.0 ./run_test.sh
#singularity exec docker://brainlife/dipy:1.1.1 ./run_test.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

echo "Convertion wmc to multiple tcks..."
sed -i '$s/}/,\n"classification":".\/classification.mat"}/' config.json
sed -i '$s/}/,\n"track":".\/tractogram.tck"}/' config.json
mkdir -p output/tcks
singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main

if [ -z "$(ls -A -- "output")" ]; then    
	echo "Conversion to tcks failed."
	exit 1
else    
	echo "Conversion to tcks done."
fi

echo "Complete"
