#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=31gb,walltime=00:30:00

set -e
set -x

#execute app
echo "Registering the tractogram to the MNI152 T1 template with ANTs..."
./run_registration.sh

echo "No examples provided. STARTING TEST..."
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run_test.sh
#SINGULARITYENV_PYTHONNOUSERSITE=true  singularity exec docker://brainlife/dipy:1.1.1 ./run_test.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.nii.gz -f
rm *.tck
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f

echo "Complete"
